x2:
  test:
    ssm:
      certificate:
        url: https://peer1.pr-commune.smartb.network/
        channelId: proudhon
        chaincodeId: ssm
---
spring:
  config:
    activate:
      on-profile:

ssm:
  chaincode:
    url: http://peer0.pr-commune.smartb.network:9090

x2:
  test:
    ssm:
      certificate:
        url: ${ssm.chaincode.url}
        channel: sandbox
        chaincode: ssm
      admin:
        name: adrien@smartb.city
        key: file:/home/adrien/.ssm/adrien@smartb.city
      agent:
        name: ssm-agent-1
        key: file:/home/adrien/.ssm/ssm-agent-1
