include:
  - project: 'fixers/cicd'
    file: 'make/.gitlab-ci.yml'

stages:
  - package

##########################################
## Tasks
##########################################

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-x2-api

front:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-x2-front

ssm-certificate-provider:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-x2-ssm-certificate-provider
