###
POST http://localhost:8080/dataChaincodeListQueryFunction
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:8082/api/getAllSsm
Accept: application/json

###
POST http://localhost:8082/api/getAllSessions
Accept: application/json
Content-Type: application/json

{
  "ssmUri": {
    "uri": "ssm:sandbox:ssm:S2WorksiteState"
  }
}


###
POST http://localhost:8082/dataSsmListQueryFunction
Accept: application/json
Content-Type: application/json

{
  "chaincodes": [
    {
      "uri": "chaincode:proudhon:ssm"
    }
  ]
}

###
http://localhost:9090/?args=ssm&cmd=query&fcn=list

###
http://localhost:9090/?args=session&cmd=query&fcn=list


###
#POST http://localhost:8082/api/sessionPerStateStats
POST https://x2.smartb.city/api/sessionPerStateStats
Accept: application/json
Content-Type: application/json

{
  "ssmUri": "ssm:proudhon:ssm:Certificates"
}

###
POST http://localhost:8082/api/sessionStatePerInterval
#POST https://x2.smartb.city/api/sessionStatePerInterval
Accept: application/json
Content-Type: application/json

{
  "ssmUri": "ssm:proudhon:ssm:Certificates"
}

###
POST http://x2.smartb.city/api/sessionPage
Accept: application/json
Content-Type: application/json

{
  "ssmUri": "ssm:proudhon:ssm:Certificates"
}


###
POST http://localhost:8082/api/sessionPerStateStats
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "protocol": "Certificates1"
  },
  "pagination": null
}

###
POST http://localhost:8082/api/getSession
Content-Type: application/json

[{
  "sessionName":"certificates-session-5-d7bdbb57-b193-4ae5-86f4-9711fac46a8a",
  "ssmUri":{"uri":"ssm:sandbox:ssm:certificates"}
}]