version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-x2
    image: smartbcity/commune-sandbox-ca:experimental
    networks:
      - bclannet-it

  orderer.bclan:
    container_name: orderer-network-x2
    image: smartbcity/commune-sandbox-orderer:experimental
    networks:
      - bclannet-it

  couchdb.bc-coop.bclan:
    container_name: couchdb-x2
    image: couchdb:3.1.0
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb
    ports:
      - 5984:5984
    networks:
      - bclannet-it
    depends_on:
      - orderer.bclan

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-x2
    image: smartbcity/commune-sandbox-peer:experimental
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-x2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - bclannet-it
    depends_on:
      - couchdb.bc-coop.bclan

  coop-rest-java:
    container_name: coop-rest-bclan-network-x2
    image: smartbcity/commune-sandbox-ssm-rest:experimental
    environment:
      - i2_jwt-issuer-uri=
    ports:
      - "9090:9090"
    networks:
      - bclannet-it
    depends_on:
      - peer0.bc-coop.bclan

  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-x2
    image: smartbcity/commune-sandbox-cli:experimental
    command: /opt/commune-sandbox/util/init.sh
    networks:
      - bclannet-it
    depends_on:
      - coop-rest-java


networks:
  bclannet-it:
    name: bclannet-it
