server:
  port: 8082

spring:
  cloud:
    function:
      web:
        path: /api
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespassword

x2:
  ssm:
    chaincodes:
      - chaincode:sandbox:ssm

ssm:
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: ssm-couchdb-unit
  chaincode:
    url: http://localhost:9090

---
spring:
  config:
    activate:
      on-profile: impactmate
x2:
  ssm:
    chaincodes:
      - chaincode:proudhon:ssm
ssm:
  couchdb:
    url: http://peer0.pr-commune.smartb.network:5984
    username: 1111
    password: 2222
    serviceName: ssm-couchdb-unit
  chaincode:
    url: "http://peer0.pr-commune.smartb.network"
    filter:
      - ssm:peer0:proudhon:ssm:Request
      - ssm:peer0:proudhon:ssm:Certificates

---
spring:
  config:
    activate:
      on-profile: x2smartb
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespassword
x2:
  ssm:
    ssm:
      - ssm:proudhon:ssm:Request
      - ssm:proudhon:ssm:Certificates

ssm:
  couchdb:
    url: http://peer0.pr-commune.smartb.network:5984
    username: 1111
    password: 2222
    serviceName: ssm-couchdb-unit
  chaincode:
    url: "http://peer0.pr-commune.smartb.network"

---
spring:
  config:
    activate:
      on-profile: local

x2:
  ssm:
    chaincodes:
      - chaincode:proudhon:ssm
    ssm:
      - ssm:proudhon:ssm:Request
      - ssm:proudhon:ssm:Certificates

ssm:
  couchdb:
    url: "http://peer0.pr-commune.smartb.network:5984"
    username: 1111
    password: 2222
    serviceName: ssm-couchdb-unit
  chaincode:
    url: "http://peer0.pr-commune.smartb.network"

---
spring:
  config:
    activate:
      on-profile: handprint-poc
x2:
  ssm:
    chaincodes:
      - chaincode:sandbox:ssm
    ssm:
      - ssm:sandbox:ssm:FundReceipt
      - ssm:sandbox:ssm:ProjectFundReceipt

ssm:
  couchdb:
    url: "http://localhost:5984"
    username: couchdb
    password: couchdb
    serviceName: x2-handprint-poc
  chaincode:
    url: "http://localhost:9090"
