server:
  port: 8082

spring:
  cloud:
    function:
      web:
        path: /api

ssm:
  couchdb:
    url: http://peer0.pr-commune.smartb.network:5984
    username: admin
    password: smartb
    serviceName: ssm-couchdb-unit